export const INCREMENT = 'INCREMENT';

export const DECREMENT = 'DECREMENT';

export const REGISTERTYPE = 'REGISTERTYPE';

export const CHANGETAB_DETAIL = 'CHANGETAB_DETAIL';

export const SETDETAIL_EQUI = 'SETDETAIL_EQUI';

export const UPDATE_SHOWWHICHTAB = 'UPDATE_SHOWWHICHTAB';
export const RENDER_CHART = 'RENDER_CHART';
export const RENDER_COP = 'RENDER_COP';
export const COPSET_PARAMS = 'COPSET_PARAMS';
export const RENDER_PRO_INDEX = 'RENDER_PRO_INDEX';
export const UPDATE_ITEMLIST_PARAMS = 'UPDATE_ITEMLIST_PARAMS';

export const COME_TO_UPLODEIMG= 'COME_TO_UPLODEIMG';
export const UPDATE_UPLOAD_IMG= 'UPDATE_UPLOAD_IMG';
export const UPDATE_SETTING_STATE= 'UPDATE_SETTING_STATE';
//������ק�ؼ����******************************
export const UPDATE_LABEL= 'UPDATE_LABEL';
export const UPDATE_CHART= 'UPDATE_CHART';
export const UPDATE_DATABLOCK= 'UPDATE_DATABLOCK';
export const UPDATE_DASHBOARD= 'UPDATE_DASHBOARD';
export const UPDATE_DATASTATE= 'UPDATE_DATASTATE';
//������ק�ؼ�ID******************************
export const UPDATE_IMG_ID= 'UPDATE_IMG_ID';
export const UPDATE_LABEL_ID= 'UPDATE_LABEL_ID';
export const UPDATE_CHART_ID= 'UPDATE_CHART_ID';
export const UPDATE_LINE_ID= 'UPDATE_LINE_ID';
export const UPDATE_DATABLOCK_ID= 'UPDATE_DATABLOCK_ID';
export const UPDATE_DASHBOARD_ID= 'UPDATE_DASHBOARD_ID';
export const UPDATE_DATASTATE_ID= 'UPDATE_DATASTATE_ID';
//***************************************************
export const DELETE_CURR_PANEL= 'DELETE_CURR_PANEL';
export const TOGGLE_SIDEBAR = 'TOGGLE_SIDEBAR';
export const RESET_WINDOWHEIGHT = 'RESET_WINDOWHEIGHT';
export const GET_EQUIPMENT_DATA = 'GET_EQUIPMENT_DATA';
export const GETPROTOCOLDATA = 'GETPROTOCOLDATA';
export const UPDATETEMPDATA = 'UPDATETEMPDATA';
export const UPDATE_FRESHTIME_DATA = 'UPDATE_FRESHTIME_DATA';
export const UPDATE_DRAGDATA_STATE = 'UPDATE_DRAGDATA_STATE';
export const UPDATE_ISADDDRAG_STATE = 'UPDATE_ISADDDRAG_STATE';
export const UPDATE_REFS = 'UPDATE_REFS';
export const UPDATE_CURRENTVIEWTAB = 'UPDATE_CURRENTVIEWTAB';
export const UPDATE_OPERATEMEMORY = 'UPDATE_OPERATEMEMORY';
export const UPDATE_CHARTCURRENTDATA= 'UPDATE_CHARTCURRENTDATA';
export const UPDATE_DATABLOCKCURRENTDATA= 'UPDATE_DATABLOCKCURRENTDATA';

export const SET_TREEMENU = 'SET_TREEMENU';
export const SET_ACTIVEMENU = 'SET_ACTIVEMENU';
export const UPDATE_VCOUNT = 'UPDATE_VCOUNT';
export const SET_IMG_SELECT = 'SET_IMG_SELECT';
export const UPDATE_CTRDATA = 'UPDATE_CTRDATA';
export const UPDATE_EXPOSELF = 'UPDATE_EXPOSELF';
export const UPDATE_EQLIST = 'UPDATE_EQLIST';
export const UPDATE_CNACTRL = 'UPDATE_CNACTRL';
